apiVersion: v1
kind: ServiceAccount
metadata:
  name: ocp-support-web
  namespace: ocp-support-web
  annotations:
    serviceaccounts.openshift.io/oauth-redirectreference.proxy: '{"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"ocp-support-web"}}'
  labels:
    app: ocp-support-web
