FROM registry.redhat.io/ubi9/nodejs-20:latest AS builder

COPY package.json tsconfig.json webpack.config.js console-extensions.json ./
RUN npm install
COPY src/ src/
RUN npm run build

FROM registry.redhat.io/ubi9/nginx-124:latest

COPY --from=builder /opt/app-root/src/dist /opt/app-root/src/
COPY nginx.conf /opt/app-root/etc/nginx.d/default.conf

CMD ["nginx", "-g", "daemon off;"]
