server {
    listen 9443 ssl;
    ssl_certificate /var/serving-cert/tls.crt;
    ssl_certificate_key /var/serving-cert/tls.key;

    root /opt/app-root/src;
    index plugin-manifest.json;

    location / {
        add_header Cache-Control "no-cache";
        try_files $uri $uri/ =404;
    }
}
